apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: delete-expired-users
  title: Delete expired Users from OpenPaaS Portal
  description: Initiate a job to delete expired users from OpenPaaS Portal
  tags:
    - housekeeping
    - user-management
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide necessary information
      required:
        - excelfile
        - subscription
      properties:
        excelfile:
          title: Inputfile
          type: string
          description: Path to github location the input excel-file resides
        description:
          title: ChangeLog-Description
          type: string
          description: Help others understand what job did
        subscription:
          title: Subscription
          type: string
          description: OpenPaaS subscription to clean
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Inputfile
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.excelfile }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.subscription }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.axa.com
        description: This is ${{ parameters.excelfile }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}