# yaml-language-server: $schema=https://raw.githubusercontent.com/backstage/backstage/refs/heads/master/plugins/scaffolder-common/src/Template.v1beta3.schema.json
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-new-subscription
  title: Create new OpenPaaS Subscription
  description: Create new OpenPaaS Subscription, setup basic CI and basic CD Environemnt
  tags:
    - openpaas
    - subscription
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide necessary information
      required:
        - subs_name
        - local_id
      properties:
        subs_name:
          title: Subscription Name
          type: string
          description: Enter name of your subscription
        description:
          title: Description
          type: string
          description: Help others understand what job did
        local_id:
          title: Local ID
          type: integer
          description: Your local id
    - title: Provide OpenPaaS Services
      properties:
        name:
          title: Services
          type: array
          description: List of services to enable for this subscription
          items:
            type: string
            enum:
              - 'openShift-project'
              - 'github-orga'
              - 'artifactory-repository'
              - 'crg'
          ui:
            widget: checkboxes
          uniqueItems: true
    - title: SetUp CI/CD Tekton ArgoCD Stack
      required:
        - namespace-release
      properties:
        namespace-release:
          title: OpenShift Project where to set up the CI/CD stack
          type: string
          description: OpenShift Project where to set up the CI/CD stack
        staging-namespace:
          title: OpenShift Project where to set up the Staging CI/CD Environment
          type: string
          description: OpenShift Project where to set up the Staging CI/CD Environment
        pipelines:
          title: Enable Pipelines for which Techniques
          type: array
          items:
            type: string
            enum:
              - 'Enable Java Maven'
              - 'Enable Java Gradle'
              - 'Enable Golang'
              - 'Enable NodeJS'
              - 'Enable Python'
              - 'Enable Container Image Build'
          uniqueItems: true
          ui:
            widget: checkboxes

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.subs_name }}
          description: ${{ parameters.description }}
          local_id: ${{ parameters.local_id }}
          owner: ${{ parameters.owner }}

  output:
    links:
      - title: Repository
        url: ${{ steps.template.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.template.output.entityRef }}
